### ISSUE TITLE
Task: log Valid Status not correct

### ISSUE THREAD

**Issue by andreasgraber** [netcloud/ncae-ansible-role#2]
log.yml:

```
---
- name: Raise a error when the STATUS is not valid
  fail:
    msg: '{{ STATUS }} is not a valid status!'
  when: STATUS not in VALID_STATUS
```

should be changed to:

```
---
- name: Raise a error when the STATUS is not valid
  fail:
    msg: '{{ LOG_STATUS }} is not a valid status!'
  when: LOG_STATUS not in VALID__LOG_STATUS
```

and vars/main.yml:

```
---
VALID_STATUS:
  - DE
  - ER
  - OR
  - RA
  - RE
VALID_LOG_STATUS:
  - IN
  - ER
  - WA
CURRENT_EXT_SERVICE: {}
CURRENT_SERVICE: {}
CURRENT_PHASE: {}
```
